// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CheckServiceabilityData, CheckServiceabilityResponses, GetChainBalanceListData, GetChainBalanceListResponses, GetCustomTokenListData, GetCustomTokenListResponses, GetIpInfoData, GetIpInfoResponses, GetTokenListCachedData, GetTokenListCachedResponses, GetTokenListData, GetTokenListResponses, GetTxnHistoryData, GetTxnHistoryResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * GetIpInfo
 */
export const getIpInfo = <ThrowOnError extends boolean = false>(options?: Options<GetIpInfoData, ThrowOnError>) => (options?.client ?? client).get<GetIpInfoResponses, unknown, ThrowOnError>({ url: '/api/wallet/v1/ip', ...options });

/**
 * GetChainBalanceList
 */
export const getChainBalanceList = <ThrowOnError extends boolean = false>(options?: Options<GetChainBalanceListData, ThrowOnError>) => (options?.client ?? client).post<GetChainBalanceListResponses, unknown, ThrowOnError>({
    url: '/api/wallet/v1/portfolio/balances',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * GetTokenListCached
 */
export const getTokenListCached = <ThrowOnError extends boolean = false>(options?: Options<GetTokenListCachedData, ThrowOnError>) => (options?.client ?? client).post<GetTokenListCachedResponses, unknown, ThrowOnError>({
    url: '/api/wallet/v1/portfolio/cached_list',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * GetCustomTokenList
 */
export const getCustomTokenList = <ThrowOnError extends boolean = false>(options?: Options<GetCustomTokenListData, ThrowOnError>) => (options?.client ?? client).post<GetCustomTokenListResponses, unknown, ThrowOnError>({
    url: '/api/wallet/v1/portfolio/custom_list',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * GetTxnHistory
 */
export const getTxnHistory = <ThrowOnError extends boolean = false>(options?: Options<GetTxnHistoryData, ThrowOnError>) => (options?.client ?? client).post<GetTxnHistoryResponses, unknown, ThrowOnError>({
    url: '/api/wallet/v1/portfolio/history',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * GetTokenList
 */
export const getTokenList = <ThrowOnError extends boolean = false>(options?: Options<GetTokenListData, ThrowOnError>) => (options?.client ?? client).post<GetTokenListResponses, unknown, ThrowOnError>({
    url: '/api/wallet/v1/portfolio/list',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * CheckServiceability
 */
export const checkServiceability = <ThrowOnError extends boolean = false>(options?: Options<CheckServiceabilityData, ThrowOnError>) => (options?.client ?? client).get<CheckServiceabilityResponses, unknown, ThrowOnError>({ url: '/api/wallet/v1/serviceability', ...options });
