// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.rampnow.io' | 'https://api.sandbox.rampnow.io' | (string & {});
};

export type AbiInfo = {
    func: string;
    params: Array<unknown>;
};

export type AddUserTokenRequest = {
    chain_id: string;
    contract_address: string;
    wallet_address: string;
};

export type AddUserTokenResponse = {
    chain_id: string;
    contract_address: string;
    decimals: number;
    id: number;
    logo_url: string;
    name: string;
    symbol: string;
    wallet_address: string;
};

export type ApproveItem = {
    price: string;
    spender: string;
    token_id: string;
    value: string;
};

export type BackendPushRequire = {
    gas_type: unknown;
};

export type BalanceChange = {
    error?: string;
    receive_nft_list: Array<unknown>;
    receive_token_list: Array<Token>;
    send_nft_list: Array<unknown>;
    send_token_list: Array<Token>;
    success: boolean;
    usd_value_change: number;
};

export type BlockChainTxn = {
    chainId: number;
    data: string;
    from: string;
    gas: string;
    gasPrice: string;
    maxFeePerGas: string;
    maxPriorityFeePerGas: string;
    nonce: string;
    to: string;
    value: string;
};

export type BridgeHistoryItem = {
    from_amount: string;
    from_chain_id: number;
    id: string;
    status: string;
    time_at: number;
    to_amount: string;
    to_chain_id: number;
    tx_hash: string;
};

export type BridgeQuote = {
    approve_contract_id: string;
    duration: number;
    from_amount: string;
    quote_key: string;
    route_id: string;
    to_amount: string;
    to_amount_min: string;
};

export type BridgeQuoteV2 = {
    bridge_id: string;
    duration: number;
    from_amount: string;
    quote_key: string;
    route_id: string;
    to_amount: string;
    to_amount_min: string;
    tools: Array<string>;
};

export type BuildBridgeTxRequest = {
    aggregator_id: string;
    bridge_id: string;
    from_chain_id: string;
    from_token_id: string;
    from_token_raw_amount: string;
    quote_key: string;
    slippage: string;
    to_chain_id: string;
    to_token_id: string;
    user_addr: string;
};

export type BuildBridgeTxResponse = {
    chainId: number;
    data: string;
    from: string;
    gasLimit: string;
    gasPrice: string;
    to: string;
    value: string;
};

export type Category = {
    id: string;
    name: string;
};

export type CexItem = {
    id: string;
    logo_url: string;
    name: string;
    site_url: string;
};

export type ChainBalance = {
    born_at: number;
    community_id: string;
    id: string;
    logo_url: string;
    name: string;
    native_token_id: string;
    usd_value: string;
    wrapped_token_id: string;
};

export type CheckServiceabilityResponse = {
    [key: string]: unknown;
};

export enum CountryCode {
    AD = 'AD',
    AE = 'AE',
    AF = 'AF',
    AG = 'AG',
    AI = 'AI',
    AL = 'AL',
    AM = 'AM',
    AN = 'AN',
    AO = 'AO',
    AQ = 'AQ',
    AR = 'AR',
    AS = 'AS',
    AT = 'AT',
    AU = 'AU',
    AW = 'AW',
    AX = 'AX',
    AZ = 'AZ',
    BA = 'BA',
    BB = 'BB',
    BD = 'BD',
    BE = 'BE',
    BF = 'BF',
    BG = 'BG',
    BH = 'BH',
    BI = 'BI',
    BJ = 'BJ',
    BL = 'BL',
    BM = 'BM',
    BN = 'BN',
    BO = 'BO',
    BQ = 'BQ',
    BR = 'BR',
    BS = 'BS',
    BT = 'BT',
    BV = 'BV',
    BW = 'BW',
    BY = 'BY',
    BZ = 'BZ',
    CA = 'CA',
    CC = 'CC',
    CD = 'CD',
    CF = 'CF',
    CG = 'CG',
    CH = 'CH',
    CI = 'CI',
    CK = 'CK',
    CL = 'CL',
    CM = 'CM',
    CN = 'CN',
    CO = 'CO',
    CR = 'CR',
    CU = 'CU',
    CV = 'CV',
    CW = 'CW',
    CX = 'CX',
    CY = 'CY',
    CZ = 'CZ',
    DE = 'DE',
    DJ = 'DJ',
    DK = 'DK',
    DM = 'DM',
    DO = 'DO',
    DZ = 'DZ',
    EC = 'EC',
    EE = 'EE',
    EG = 'EG',
    EH = 'EH',
    ER = 'ER',
    ES = 'ES',
    ET = 'ET',
    FI = 'FI',
    FJ = 'FJ',
    FK = 'FK',
    FM = 'FM',
    FO = 'FO',
    FR = 'FR',
    GA = 'GA',
    GB = 'GB',
    GD = 'GD',
    GE = 'GE',
    GF = 'GF',
    GG = 'GG',
    GH = 'GH',
    GI = 'GI',
    GL = 'GL',
    GM = 'GM',
    GN = 'GN',
    GP = 'GP',
    GQ = 'GQ',
    GR = 'GR',
    GS = 'GS',
    GT = 'GT',
    GU = 'GU',
    GW = 'GW',
    GY = 'GY',
    HK = 'HK',
    HM = 'HM',
    HN = 'HN',
    HR = 'HR',
    HT = 'HT',
    HU = 'HU',
    ID = 'ID',
    IE = 'IE',
    IL = 'IL',
    IM = 'IM',
    IN = 'IN',
    IO = 'IO',
    IQ = 'IQ',
    IR = 'IR',
    IS = 'IS',
    IT = 'IT',
    JE = 'JE',
    JM = 'JM',
    JO = 'JO',
    JP = 'JP',
    KE = 'KE',
    KG = 'KG',
    KH = 'KH',
    KI = 'KI',
    KM = 'KM',
    KN = 'KN',
    KP = 'KP',
    KR = 'KR',
    KW = 'KW',
    KY = 'KY',
    KZ = 'KZ',
    LA = 'LA',
    LB = 'LB',
    LC = 'LC',
    LI = 'LI',
    LK = 'LK',
    LR = 'LR',
    LS = 'LS',
    LT = 'LT',
    LU = 'LU',
    LV = 'LV',
    LY = 'LY',
    MA = 'MA',
    MC = 'MC',
    MD = 'MD',
    ME = 'ME',
    MF = 'MF',
    MG = 'MG',
    MH = 'MH',
    MK = 'MK',
    ML = 'ML',
    MM = 'MM',
    MN = 'MN',
    MO = 'MO',
    MP = 'MP',
    MQ = 'MQ',
    MR = 'MR',
    MS = 'MS',
    MT = 'MT',
    MU = 'MU',
    MV = 'MV',
    MW = 'MW',
    MX = 'MX',
    MY = 'MY',
    MZ = 'MZ',
    NA = 'NA',
    NC = 'NC',
    NE = 'NE',
    NF = 'NF',
    NG = 'NG',
    NI = 'NI',
    NL = 'NL',
    NO = 'NO',
    NP = 'NP',
    NR = 'NR',
    NU = 'NU',
    NZ = 'NZ',
    OM = 'OM',
    PA = 'PA',
    PE = 'PE',
    PF = 'PF',
    PG = 'PG',
    PH = 'PH',
    PK = 'PK',
    PL = 'PL',
    PM = 'PM',
    PN = 'PN',
    PR = 'PR',
    PS = 'PS',
    PT = 'PT',
    PW = 'PW',
    PY = 'PY',
    QA = 'QA',
    RE = 'RE',
    RO = 'RO',
    RS = 'RS',
    RU = 'RU',
    RW = 'RW',
    SA = 'SA',
    SB = 'SB',
    SC = 'SC',
    SD = 'SD',
    SE = 'SE',
    SG = 'SG',
    SH = 'SH',
    SI = 'SI',
    SJ = 'SJ',
    SK = 'SK',
    SL = 'SL',
    SM = 'SM',
    SN = 'SN',
    SO = 'SO',
    SR = 'SR',
    SS = 'SS',
    ST = 'ST',
    SV = 'SV',
    SX = 'SX',
    SY = 'SY',
    SZ = 'SZ',
    TC = 'TC',
    TD = 'TD',
    TF = 'TF',
    TG = 'TG',
    TH = 'TH',
    TJ = 'TJ',
    TK = 'TK',
    TL = 'TL',
    TM = 'TM',
    TN = 'TN',
    TO = 'TO',
    TR = 'TR',
    TT = 'TT',
    TV = 'TV',
    TW = 'TW',
    TZ = 'TZ',
    UA = 'UA',
    UG = 'UG',
    UM = 'UM',
    US = 'US',
    UY = 'UY',
    UZ = 'UZ',
    VA = 'VA',
    VC = 'VC',
    VE = 'VE',
    VG = 'VG',
    VI = 'VI',
    VN = 'VN',
    VU = 'VU',
    WF = 'WF',
    WS = 'WS',
    XK = 'XK',
    XX = 'XX',
    YE = 'YE',
    YT = 'YT',
    YU = 'YU',
    ZA = 'ZA',
    ZM = 'ZM',
    ZW = 'ZW'
}

export enum CurrencyCode {
    AAAFISH = 'AAAFISH',
    AAVE = 'AAVE',
    ADA = 'ADA',
    AED = 'AED',
    AERO = 'AERO',
    AETH = 'AETH',
    AFN = 'AFN',
    AFSUI = 'AFSUI',
    AGNOEURE = 'AGNOEURE',
    AGNOGNO = 'AGNOGNO',
    AGNOUSDC = 'AGNOUSDC',
    AGNOWETH = 'AGNOWETH',
    AI16Z = 'AI16Z',
    AIOT = 'AIOT',
    AIXBT = 'AIXBT',
    ALEO = 'ALEO',
    ALGO = 'ALGO',
    ALI = 'ALI',
    ALKIMI = 'ALKIMI',
    ALL = 'ALL',
    ALUSD = 'ALUSD',
    AMD = 'AMD',
    AMP = 'AMP',
    ANG = 'ANG',
    ANIMA = 'ANIMA',
    ANIME = 'ANIME',
    ANKR = 'ANKR',
    ANON = 'ANON',
    AOA = 'AOA',
    APE = 'APE',
    API4 = 'API4',
    ARB = 'ARB',
    ARENA = 'ARENA',
    ARS = 'ARS',
    ASONUSDC = 'ASONUSDC',
    ASTER = 'ASTER',
    ASTR = 'ASTR',
    AT = 'AT',
    ATA = 'ATA',
    ATH = 'ATH',
    AUD = 'AUD',
    AURA = 'AURA',
    AUSD = 'AUSD',
    AVAX = 'AVAX',
    AVNT = 'AVNT',
    AWG = 'AWG',
    AXLUSDC = 'AXLUSDC',
    AXS = 'AXS',
    AZN = 'AZN',
    B = 'B',
    B3 = 'B3',
    B4 = 'B4',
    BADGER = 'BADGER',
    BAL = 'BAL',
    BAM = 'BAM',
    BANANA = 'BANANA',
    BAO = 'BAO',
    BAT = 'BAT',
    BB = 'BB',
    BBD = 'BBD',
    BCH = 'BCH',
    BCSPX = 'BCSPX',
    BDT = 'BDT',
    BEL = 'BEL',
    BEPE = 'BEPE',
    BERA = 'BERA',
    BERAETH = 'BERAETH',
    BES = 'BES',
    BETS = 'BETS',
    BGN = 'BGN',
    BHD = 'BHD',
    BIF = 'BIF',
    BIO = 'BIO',
    BITCOIN = 'BITCOIN',
    BLAST = 'BLAST',
    BLUAI = 'BLUAI',
    BMD = 'BMD',
    BNB = 'BNB',
    BND = 'BND',
    BOB = 'BOB',
    BOL = 'BOL',
    BOLD = 'BOLD',
    BONK = 'BONK',
    BORG = 'BORG',
    BOSON = 'BOSON',
    BRETT = 'BRETT',
    BRIGHT = 'BRIGHT',
    BRL = 'BRL',
    BRLA = 'BRLA',
    BRLY = 'BRLY',
    BROCCOLI = 'BROCCOLI',
    BRUSH = 'BRUSH',
    BSD = 'BSD',
    BSV = 'BSV',
    BTC = 'BTC',
    BTCN = 'BTCN',
    BTN = 'BTN',
    BTT = 'BTT',
    BUCK = 'BUCK',
    BUSD = 'BUSD',
    BWP = 'BWP',
    BYN = 'BYN',
    BYUSD = 'BYUSD',
    BZD = 'BZD',
    BZZ = 'BZZ',
    CAD = 'CAD',
    CAKE = 'CAKE',
    CARV = 'CARV',
    CAT = 'CAT',
    CATI = 'CATI',
    CAUD = 'CAUD',
    CAW = 'CAW',
    CBETH = 'CBETH',
    CCAD = 'CCAD',
    CCHF = 'CCHF',
    CDF = 'CDF',
    CELO = 'CELO',
    CEUR = 'CEUR',
    CGBP = 'CGBP',
    CGHS = 'CGHS',
    CGX = 'CGX',
    CHE = 'CHE',
    CHF = 'CHF',
    CHW = 'CHW',
    CHZ = 'CHZ',
    CJPY = 'CJPY',
    CLANKER = 'CLANKER',
    CLF = 'CLF',
    CLP = 'CLP',
    CMETH = 'CMETH',
    CNDY = 'CNDY',
    CNGN = 'CNGN',
    CNY = 'CNY',
    COAI = 'COAI',
    COMP = 'COMP',
    COOK = 'COOK',
    COOKIE = 'COOKIE',
    COP = 'COP',
    COQ = 'COQ',
    COU = 'COU',
    COW = 'COW',
    CRC = 'CRC',
    CRO = 'CRO',
    CROAK = 'CROAK',
    CRV = 'CRV',
    CRVUSD = 'CRVUSD',
    CST = 'CST',
    CTX = 'CTX',
    CUC = 'CUC',
    CUP = 'CUP',
    CUSD = 'CUSD',
    CVE = 'CVE',
    CVX = 'CVX',
    CZAR = 'CZAR',
    CZK = 'CZK',
    DAI = 'DAI',
    DAIE = 'DAIE',
    DAR = 'DAR',
    DATA = 'DATA',
    DEGEN = 'DEGEN',
    DIMO = 'DIMO',
    DIP = 'DIP',
    DJF = 'DJF',
    DKK = 'DKK',
    DMC = 'DMC',
    DOG = 'DOG',
    DOGE = 'DOGE',
    DOLO = 'DOLO',
    DOP = 'DOP',
    DRIFT = 'DRIFT',
    DS = 'DS',
    DTC = 'DTC',
    DUSD = 'DUSD',
    DUSX = 'DUSX',
    DXD = 'DXD',
    DZD = 'DZD',
    EBASIS = 'EBASIS',
    EBLUE = 'EBLUE',
    EBTC = 'EBTC',
    EDU = 'EDU',
    EGP = 'EGP',
    EGUSDC = 'EGUSDC',
    EIGEN = 'EIGEN',
    ENA = 'ENA',
    ENS = 'ENS',
    EOS = 'EOS',
    ERN = 'ERN',
    ESUI = 'ESUI',
    ETB = 'ETB',
    ETH = 'ETH',
    ETHFI = 'ETHFI',
    ETHIX = 'ETHIX',
    ETHS = 'ETHS',
    ETHX = 'ETHX',
    EUL = 'EUL',
    EUR = 'EUR',
    EURA = 'EURA',
    EURC = 'EURC',
    EURCV = 'EURCV',
    EURE = 'EURE',
    EUSD = 'EUSD',
    EZETH = 'EZETH',
    FAI = 'FAI',
    FARTCOIN = 'FARTCOIN',
    FBTC = 'FBTC',
    FDUSD = 'FDUSD',
    FEB = 'FEB',
    FF = 'FF',
    FISH = 'FISH',
    FJD = 'FJD',
    FKP = 'FKP',
    FLOCK = 'FLOCK',
    FLOW = 'FLOW',
    FLR = 'FLR',
    FLSUI = 'FLSUI',
    FLUID = 'FLUID',
    FLY = 'FLY',
    FOX = 'FOX',
    FOXY = 'FOXY',
    FRAX = 'FRAX',
    FRED = 'FRED',
    FRXETH = 'FRXETH',
    FRXUSD = 'FRXUSD',
    FTM = 'FTM',
    FTX = 'FTX',
    FUSE = 'FUSE',
    FXS = 'FXS',
    G = 'G',
    GALA = 'GALA',
    GBP = 'GBP',
    GBPE = 'GBPE',
    GEL = 'GEL',
    GHO = 'GHO',
    GHS = 'GHS',
    GHST = 'GHST',
    GIP = 'GIP',
    GIV = 'GIV',
    GLM = 'GLM',
    GLMR = 'GLMR',
    GMD = 'GMD',
    GMT = 'GMT',
    GMX = 'GMX',
    GNF = 'GNF',
    GNO = 'GNO',
    GNS = 'GNS',
    GOG = 'GOG',
    GOHOME = 'GOHOME',
    GRAI = 'GRAI',
    GRASS = 'GRASS',
    GRT = 'GRT',
    GTQ = 'GTQ',
    GYD = 'GYD',
    HASUI = 'HASUI',
    HAUS = 'HAUS',
    HAWAL = 'HAWAL',
    HEGIC = 'HEGIC',
    HENLO = 'HENLO',
    HEX = 'HEX',
    HIVEWATER = 'HIVEWATER',
    HKD = 'HKD',
    HNL = 'HNL',
    HNY = 'HNY',
    HOLD = 'HOLD',
    HOLO = 'HOLO',
    HOME = 'HOME',
    HONEY = 'HONEY',
    HOPR = 'HOPR',
    HRK = 'HRK',
    HTG = 'HTG',
    HUF = 'HUF',
    HYPE = 'HYPE',
    HYPER = 'HYPER',
    IBERA = 'IBERA',
    IBEX = 'IBEX',
    IBGT = 'IBGT',
    ICP = 'ICP',
    IDR = 'IDR',
    IDRX = 'IDRX',
    ILS = 'ILS',
    IMX = 'IMX',
    INC = 'INC',
    INCH1 = 'INCH1',
    INJ = 'INJ',
    INR = 'INR',
    IQD = 'IQD',
    IRR = 'IRR',
    ISK = 'ISK',
    IXT = 'IXT',
    JAIHOZB = 'JAIHOZB',
    JASMY = 'JASMY',
    JLP = 'JLP',
    JMD = 'JMD',
    JOD = 'JOD',
    JOE = 'JOE',
    JPY = 'JPY',
    JTO = 'JTO',
    JUP = 'JUP',
    KAIA = 'KAIA',
    KAITO = 'KAITO',
    KAT = 'KAT',
    KERNEL = 'KERNEL',
    KES = 'KES',
    KGS = 'KGS',
    KHR = 'KHR',
    KITTY = 'KITTY',
    KMF = 'KMF',
    KMNO = 'KMNO',
    KNC = 'KNC',
    KOGE = 'KOGE',
    KOGIN = 'KOGIN',
    KOI = 'KOI',
    KPW = 'KPW',
    KRW = 'KRW',
    KTA = 'KTA',
    KWD = 'KWD',
    KYD = 'KYD',
    KZT = 'KZT',
    LAK = 'LAK',
    LAYER = 'LAYER',
    LBGT = 'LBGT',
    LBP = 'LBP',
    LBTC = 'LBTC',
    LDO = 'LDO',
    LEND = 'LEND',
    LIGHT = 'LIGHT',
    LINEA = 'LINEA',
    LINK = 'LINK',
    LINKE = 'LINKE',
    LION = 'LION',
    LKR = 'LKR',
    LONG = 'LONG',
    LPT = 'LPT',
    LPUSS = 'LPUSS',
    LRD = 'LRD',
    LSL = 'LSL',
    LTC = 'LTC',
    LUA = 'LUA',
    LUAUSD = 'LUAUSD',
    LUBE = 'LUBE',
    LUGA = 'LUGA',
    LUMIA = 'LUMIA',
    LUMOS = 'LUMOS',
    LYD = 'LYD',
    LYNX = 'LYNX',
    LYU = 'LYU',
    MAD = 'MAD',
    MAGIC = 'MAGIC',
    MAI = 'MAI',
    MANA = 'MANA',
    MANTLE = 'MANTLE',
    MASK = 'MASK',
    MATIC = 'MATIC',
    MAVIA = 'MAVIA',
    MBASIS = 'MBASIS',
    MBOX = 'MBOX',
    MBTC = 'MBTC',
    MDL = 'MDL',
    ME = 'ME',
    MELANIA = 'MELANIA',
    MEMEFI = 'MEMEFI',
    MENDI = 'MENDI',
    MET = 'MET',
    METH = 'METH',
    METIS = 'METIS',
    METRO = 'METRO',
    MEW = 'MEW',
    MGA = 'MGA',
    MGT = 'MGT',
    MIM = 'MIM',
    MINU = 'MINU',
    MIRA = 'MIRA',
    MIVA = 'MIVA',
    MKD = 'MKD',
    MMEV = 'MMEV',
    MMK = 'MMK',
    MNT = 'MNT',
    MOCA = 'MOCA',
    MODE = 'MODE',
    MOE = 'MOE',
    MOG = 'MOG',
    MON = 'MON',
    MOODENG = 'MOODENG',
    MOONY = 'MOONY',
    MOP = 'MOP',
    MORPHO = 'MORPHO',
    MOVE = 'MOVE',
    MOVR = 'MOVR',
    MPLX = 'MPLX',
    MRU = 'MRU',
    MTBILL = 'MTBILL',
    MUBARAK = 'MUBARAK',
    MUR = 'MUR',
    MUSD = 'MUSD',
    MUSDC = 'MUSDC',
    MUSDT = 'MUSDT',
    MUTE = 'MUTE',
    MVR = 'MVR',
    MWK = 'MWK',
    MX = 'MX',
    MXN = 'MXN',
    MXV = 'MXV',
    MYR = 'MYR',
    MYX = 'MYX',
    MZN = 'MZN',
    NAD = 'NAD',
    NAVX = 'NAVX',
    NEAR = 'NEAR',
    NECT = 'NECT',
    NEX = 'NEX',
    NEXO = 'NEXO',
    NFTL = 'NFTL',
    NGN = 'NGN',
    NILE = 'NILE',
    NIO = 'NIO',
    NOICE = 'NOICE',
    NOK = 'NOK',
    NON = 'NON',
    NPR = 'NPR',
    NS = 'NS',
    NSASTR = 'NSASTR',
    NUTS = 'NUTS',
    NXPC = 'NXPC',
    NZD = 'NZD',
    OBT = 'OBT',
    OL = 'OL',
    OLAS = 'OLAS',
    OM = 'OM',
    OMR = 'OMR',
    ONDO = 'ONDO',
    OP = 'OP',
    ORA = 'ORA',
    ORBS = 'ORBS',
    ORBSA = 'ORBSA',
    ORCA = 'ORCA',
    ORDER = 'ORDER',
    OS = 'OS',
    OSAK = 'OSAK',
    OUSDT = 'OUSDT',
    OVR = 'OVR',
    OX = 'OX',
    PAB = 'PAB',
    PAXG = 'PAXG',
    PEN = 'PEN',
    PENDLE = 'PENDLE',
    PENGU = 'PENGU',
    PEOPLE = 'PEOPLE',
    PEPE = 'PEPE',
    PETH = 'PETH',
    PGK = 'PGK',
    PHP = 'PHP',
    PIXEL = 'PIXEL',
    PKR = 'PKR',
    PLN = 'PLN',
    PLS = 'PLS',
    PLSX = 'PLSX',
    PLU = 'PLU',
    PNG = 'PNG',
    PNK = 'PNK',
    PNUT = 'PNUT',
    POL = 'POL',
    POOL = 'POOL',
    POPCAT = 'POPCAT',
    POPFISH = 'POPFISH',
    PRIME = 'PRIME',
    PROMPT = 'PROMPT',
    PROVE = 'PROVE',
    PUFETH = 'PUFETH',
    PUFF = 'PUFF',
    PUMP = 'PUMP',
    PUMPBTC = 'PUMPBTC',
    PUNK = 'PUNK',
    PUSD = 'PUSD',
    PXETH = 'PXETH',
    PYG = 'PYG',
    PYR = 'PYR',
    PYTH = 'PYTH',
    PYUSD = 'PYUSD',
    QAR = 'QAR',
    QI = 'QI',
    QNT = 'QNT',
    QUICK = 'QUICK',
    RAID = 'RAID',
    RAMEN = 'RAMEN',
    RAY = 'RAY',
    RBTC = 'RBTC',
    RCO = 'RCO',
    RDNT = 'RDNT',
    RECALL = 'RECALL',
    RENDER = 'RENDER',
    REQ = 'REQ',
    RETH = 'RETH',
    REX = 'REX',
    REX34 = 'REX34',
    RIF = 'RIF',
    RLUSD = 'RLUSD',
    RNDR = 'RNDR',
    RON = 'RON',
    RONIN = 'RONIN',
    RONOUT = 'RONOUT',
    RSD = 'RSD',
    RSETH = 'RSETH',
    RSR = 'RSR',
    RUB = 'RUB',
    RUSD = 'RUSD',
    RWF = 'RWF',
    RZR = 'RZR',
    S = 'S',
    SAND = 'SAND',
    SAPIEN = 'SAPIEN',
    SAR = 'SAR',
    SBD = 'SBD',
    SCBTC = 'SCBTC',
    SCR = 'SCR',
    SCROLL = 'SCROLL',
    SCUSD = 'SCUSD',
    SD = 'SD',
    SDAI = 'SDAI',
    SDEX = 'SDEX',
    SDG = 'SDG',
    SEI = 'SEI',
    SEK = 'SEK',
    SFRAX = 'SFRAX',
    SFRXETH = 'SFRXETH',
    SGD = 'SGD',
    SHADOW = 'SHADOW',
    SHIB = 'SHIB',
    SHP = 'SHP',
    SHRAP = 'SHRAP',
    SIGN = 'SIGN',
    SILO = 'SILO',
    SIS = 'SIS',
    SKATE = 'SKATE',
    SKY = 'SKY',
    SKYDROME = 'SKYDROME',
    SLL = 'SLL',
    SLP = 'SLP',
    SLR = 'SLR',
    SNX = 'SNX',
    SOGNI = 'SOGNI',
    SOIL = 'SOIL',
    SOL = 'SOL',
    SOLVBTC = 'SOLVBTC',
    SOPH = 'SOPH',
    SOS = 'SOS',
    SOV = 'SOV',
    SPA = 'SPA',
    SPACE = 'SPACE',
    SPELL = 'SPELL',
    SPK = 'SPK',
    SPLO = 'SPLO',
    SPX = 'SPX',
    SRD = 'SRD',
    SSP = 'SSP',
    SSUI = 'SSUI',
    STAKE = 'STAKE',
    STAR = 'STAR',
    STBGT = 'STBGT',
    STBL = 'STBL',
    STDOT = 'STDOT',
    STEUR = 'STEUR',
    STG = 'STG',
    STGUSDC = 'STGUSDC',
    STN = 'STN',
    STONE = 'STONE',
    STS = 'STS',
    STXTZ = 'STXTZ',
    SUI = 'SUI',
    SUIB = 'SUIB',
    SUIGMA = 'SUIGMA',
    SUITORO = 'SUITORO',
    SUITRUMP = 'SUITRUMP',
    SUIYAN = 'SUIYAN',
    SUKU = 'SUKU',
    SUPERFARM = 'SUPERFARM',
    SUPERSUI = 'SUPERSUI',
    SUPERVERSE = 'SUPERVERSE',
    SURE = 'SURE',
    SURF = 'SURF',
    SUSDAI = 'SUSDAI',
    SUSDE = 'SUSDE',
    SUSDP = 'SUSDP',
    SUSHI = 'SUSHI',
    SVC = 'SVC',
    SWAP = 'SWAP',
    SWAPE = 'SWAPE',
    SWORD = 'SWORD',
    SYP = 'SYP',
    SYRUP = 'SYRUP',
    SZL = 'SZL',
    TBTC = 'TBTC',
    TEL = 'TEL',
    THB = 'THB',
    THE = 'THE',
    TIBBIR = 'TIBBIR',
    TJS = 'TJS',
    TMT = 'TMT',
    TND = 'TND',
    TON = 'TON',
    TOP = 'TOP',
    TOSHI = 'TOSHI',
    TOWER = 'TOWER',
    TOWNS = 'TOWNS',
    TRAC = 'TRAC',
    TRADE = 'TRADE',
    TRILLIONS = 'TRILLIONS',
    TROLL = 'TROLL',
    TRUMP = 'TRUMP',
    TRX = 'TRX',
    TRY = 'TRY',
    TTD = 'TTD',
    TUSD = 'TUSD',
    TWD = 'TWD',
    TWT = 'TWT',
    TZS = 'TZS',
    UAH = 'UAH',
    UGM = 'UGM',
    UGX = 'UGX',
    UNI = 'UNI',
    UNIBTC = 'UNIBTC',
    UNIETH = 'UNIETH',
    UP = 'UP',
    UPSUI = 'UPSUI',
    USD = 'USD',
    USD0 = 'USD0',
    USD1 = 'USD1',
    USD2 = 'USD2',
    USDA = 'USDA',
    USDAF = 'USDAF',
    USDAI = 'USDAI',
    USDB = 'USDB',
    USDBC = 'USDBC',
    USDC = 'USDC',
    USDCARB = 'USDCARB',
    USDCB = 'USDCB',
    USDCBS = 'USDCBS',
    USDCE = 'USDCE',
    USDCEG = 'USDCEG',
    USDCET = 'USDCET',
    USDCN = 'USDCN',
    USDCPO = 'USDCPO',
    USDCSGATE = 'USDCSGATE',
    USDCX = 'USDCX',
    USDD = 'USDD',
    USDE = 'USDE',
    USDF = 'USDF',
    USDG = 'USDG',
    USDGLO = 'USDGLO',
    USDH = 'USDH',
    USDHL = 'USDHL',
    USDL = 'USDL',
    USDM = 'USDM',
    USDN = 'USDN',
    USDOVERNIGHTFI = 'USDOVERNIGHTFI',
    USDP = 'USDP',
    USDQ = 'USDQ',
    USDR = 'USDR',
    USDS = 'USDS',
    USDSTAR = 'USDSTAR',
    USDT = 'USDT',
    USDT0 = 'USDT0',
    USDT0B = 'USDT0B',
    USDTB = 'USDTB',
    USDTE = 'USDTE',
    USDTG = 'USDTG',
    USDTSTARGATE = 'USDTSTARGATE',
    USDU = 'USDU',
    USDV = 'USDV',
    USDX = 'USDX',
    USDXL = 'USDXL',
    USDY = 'USDY',
    USDZ = 'USDZ',
    US_DT = 'USDt',
    USEFUL = 'USEFUL',
    USELESS = 'USELESS',
    USH = 'USH',
    USHETH = 'USHETH',
    USN = 'USN',
    USOL = 'USOL',
    USR = 'USR',
    UST = 'UST',
    USTAX = 'USTAX',
    USTWH = 'USTWH',
    USUALX = 'USUALX',
    USX = 'USX',
    USXC = 'USXC',
    UYI = 'UYI',
    UYU = 'UYU',
    UZS = 'UZS',
    VAI = 'VAI',
    VAN = 'VAN',
    VANA = 'VANA',
    VASTR = 'VASTR',
    VC = 'VC',
    VCHF = 'VCHF',
    VEF = 'VEF',
    VELO = 'VELO',
    VES = 'VES',
    VEUR = 'VEUR',
    VFY = 'VFY',
    VIRTUAL = 'VIRTUAL',
    VLR = 'VLR',
    VND = 'VND',
    VOXEL = 'VOXEL',
    VS = 'VS',
    VSN = 'VSN',
    VSUI = 'VSUI',
    VUV = 'VUV',
    VVV = 'VVV',
    W = 'W',
    WAGMI = 'WAGMI',
    WAGMIS = 'WAGMIS',
    WAGNOGNO = 'WAGNOGNO',
    WAGNOWETH = 'WAGNOWETH',
    WAGNOWSTETH = 'WAGNOWSTETH',
    WAL = 'WAL',
    WAPE = 'WAPE',
    WATER = 'WATER',
    WBERA = 'WBERA',
    WBNB = 'WBNB',
    WBTC = 'WBTC',
    WBTCN = 'WBTCN',
    WCRO = 'WCRO',
    WEETH = 'WEETH',
    WETH = 'WETH',
    WF = 'WF',
    WFRAX = 'WFRAX',
    WG = 'WG',
    WGLMR = 'WGLMR',
    WIF = 'WIF',
    WIMX = 'WIMX',
    WISP = 'WISP',
    WLD = 'WLD',
    WLFI = 'WLFI',
    WMETIS = 'WMETIS',
    WMNT = 'WMNT',
    WMON = 'WMON',
    WMTX = 'WMTX',
    WOO = 'WOO',
    WPLS = 'WPLS',
    WPLU = 'WPLU',
    WRON = 'WRON',
    WRSETH = 'WRSETH',
    WSAFU = 'WSAFU',
    WSEI = 'WSEI',
    WSLT = 'WSLT',
    WSRUSD = 'WSRUSD',
    WST = 'WST',
    WSTASTR = 'WSTASTR',
    WSTETH = 'WSTETH',
    WUF = 'WUF',
    WXDAI = 'WXDAI',
    WXPL = 'WXPL',
    WXTZ = 'WXTZ',
    X34 = 'X34',
    XAF = 'XAF',
    XAI = 'XAI',
    XAUM = 'XAUM',
    XAUT = 'XAUT',
    XAUT0 = 'XAUT0',
    XBG = 'XBG',
    XBTC = 'XBTC',
    XCD = 'XCD',
    XCDOT = 'XCDOT',
    XCMANTA = 'XCMANTA',
    XCN = 'XCN',
    XDAI = 'XDAI',
    XDC = 'XDC',
    XDR = 'XDR',
    XLM = 'XLM',
    XOF = 'XOF',
    XPF = 'XPF',
    XPIN = 'XPIN',
    XPL = 'XPL',
    XSGD = 'XSGD',
    XSOLVBTC = 'XSOLVBTC',
    XSU = 'XSU',
    XTZ = 'XTZ',
    XU3O8 = 'XU3O8',
    XUA = 'XUA',
    XUSD = 'XUSD',
    XVS = 'XVS',
    YAPSUI = 'YAPSUI',
    YER = 'YER',
    YES = 'YES',
    YGG = 'YGG',
    YU = 'YU',
    YUD = 'YUD',
    YZY = 'YZY',
    Z2 = 'Z2',
    ZAR = 'ZAR',
    ZAT = 'ZAT',
    ZBCN = 'ZBCN',
    ZBU = 'ZBU',
    ZENGAR = 'ZENGAR',
    ZENT = 'ZENT',
    ZERO = 'ZERO',
    ZF = 'ZF',
    ZK = 'ZK',
    ZKDOGE = 'ZKDOGE',
    ZMW = 'ZMW',
    ZORA = 'ZORA',
    ZRO = 'ZRO',
    ZRX = 'ZRX',
    ZWL = 'ZWL'
}

export type ExecuteSwapRequest = {
    from_address: string;
    route_id: string;
    tx_hash: string;
};

export type ExecuteSwapResponse = {
    status: string;
    transaction_hash: string;
};

/**
 * FeeCost represents fee cost breakdownGetSwapQuoteResponse represents the swap quote response
 */
export type FeeCost = {
    amount: string;
    amount_usd: string;
    name: string;
    percentage: string;
};

export type FeeCostType2 = {
    amount: string;
    amountUSD: string;
    description: string;
    feeSplit?: FeeSplit;
    included: boolean;
    name: string;
    percentage: string;
    token?: TokenInfo;
};

export type FeeSplit = {
    integratorFee: string;
    lifiFee: string;
};

export type GasAccountCost = {
    estimate_tx_cost: number;
    gas_cost: number;
    total_cost: number;
    tx_cost: number;
};

/**
 * GasCost represents gas cost breakdownFeeCost represents fee cost breakdown
 */
export type GasCost = {
    amount: string;
    amount_usd: string;
};

export type GasCostType2 = {
    amount: string;
    amountUSD: string;
    estimate: string;
    limit: string;
    price: string;
    token?: TokenInfo;
    type: string;
};

export type GasInfo = {
    error?: string;
    gas_limit: number;
    gas_ratio: number;
    gas_used: number;
    success: boolean;
};

export type GasLevel = {
    estimated_seconds: number;
    front_tx_count: number;
    level: string;
    price?: string;
    priority_price?: string;
};

export type GetBridgeHistoryListResponse = {
    history_list: Array<BridgeHistoryItem>;
    total_cnt: number;
};

export type GetBridgeQuoteListResponse = {
    quotes: Array<BridgeQuote>;
};

export type GetBridgeQuoteV2Response = {
    quotes: Array<BridgeQuoteV2>;
};

export type GetChainBalanceListResponse = {
    chain_list: Array<ChainBalance>;
    error_code: number;
    evm_usd_value: string;
    total_usd_value: string;
};

export type GetChainRpcResponse = {
    message: string;
    rpcs: Array<RpcDefaultItem>;
    status: string;
};

export type GetCheckTxsRequest = {
    account_id: string;
    tx_list: Array<Transaction>;
};

export type GetCheckTxsResponse = {
    balance_is_enough: boolean;
    chain_not_support: boolean;
    err_msg: string;
    gas_account_cost?: GasAccountCost;
    is_gas_account: boolean;
};

export type GetCustomTokenListRequest = {
    address: string;
    assets: Array<string>;
};

export type GetCustomTokenListResponse = {
    list: Array<Token>;
};

export type GetDepositStatusResponse = {
    deposit_id: string;
    status: string;
    tx_hash: string;
};

export type GetDexSwapQuoteResponse = {
    /**
     * Address to approve token to
     */
    dex_approve_to: string;
    /**
     * Fee description
     */
    dex_fee_desc?: string;
    /**
     * Encoded calldata for the swap
     */
    dex_swap_calldata: string;
    /**
     * Address to send swap to
     */
    dex_swap_to: string;
    /**
     * Execution duration in seconds
     */
    execution_duration: number;
    /**
     * Fee costs breakdown
     */
    fee_costs: Array<FeeCost>;
    /**
     * Gas costs breakdown
     */
    gas_costs: Array<GasCost>;
    /**
     * Gas used for the transaction
     */
    gas_used: number;
    /**
     * Whether swap is successful
     */
    is_success: boolean;
    /**
     * Whether token needs wrapping
     */
    is_wrapped: boolean;
    /**
     * Token being paid
     */
    pay_token?: TokenType2;
    /**
     * Token being received
     */
    receive_token?: TokenType2;
    /**
     * Raw amount received (in wei/smallest unit)
     */
    receive_token_raw_amount: number;
};

export type GetEthRpcRequest = {
    chain_id: string;
    method: string;
    origin: string;
    params: Array<unknown>;
};

export type GetEthRpcResponse = {
    error?: RpcError;
    id: unknown;
    jsonrpc: string;
    result: unknown;
};

export type GetGasFeeRequest = {
    chain_id: string;
    custom_gas: string;
    tx?: BlockChainTxn;
};

export type GetGasFeeResponse = {
    gas_levels: Array<GasLevel>;
};

export type GetGasPriceStatsResponse = {
    median?: string;
};

export type GetHypermidQuoteResponse = {
    quote: unknown;
};

export type GetHypermidRoutesResponse = {
    routes: Array<Route>;
};

export type GetIpInfoResponse = {
    country: CountryCode;
};

export type GetParseTxRequest = {
    chain_id: string;
    origin: string;
    tx: Transaction;
    user_addr: string;
};

export type GetParseTxResponse = {
    action?: ParseTxActionType;
    contract_call?: ParseTxContractCallType;
    log_id: number;
};

export type GetPreExecTxnRequest = {
    origin: string;
    pending_tx_list: Array<BlockChainTxn>;
    tx: BlockChainTxn;
    update_nonce: boolean;
    user_addr: string;
};

export type GetPreExecTxnResponse = {
    abi?: AbiInfo;
    abi_str?: string;
    balance_change?: BalanceChange;
    gas?: GasInfo;
    is_gnosis: boolean;
    native_token?: Token;
    pre_exec?: PreExecStatus;
    pre_exec_version: string;
    trace_id?: string;
    type_call?: TypeCallInfo;
    type_cancel_tx?: TypeCancelTx;
    type_send?: TypeSendInfo;
    type_token_approval?: TypeTokenApprovalInfo;
};

export type GetSearchTokenResponse = {
    list: Array<Token>;
};

export type GetSubmitTxRequest = {
    backend_push_require?: BackendPushRequire;
    context: TxContext;
    mev_share_model: string;
};

export type GetSubmitTxResponse = {
    access_token: unknown;
    err: string;
    tx_id: string;
};

export type GetSwapBalancesResponse = {
    balances: Array<SwapBalanceItem>;
};

export type GetSwapChainsResponse = {
    chains: Array<SwapChain>;
};

export type GetSwapConnectionsResponse = {
    connections: Array<SwapConnection>;
};

export type GetSwapGasPricesResponse = {
    gas_prices: {
        [key: string]: SwapChainGasPrice;
    };
};

export type GetSwapQuoteResponse = {
    quote: unknown;
};

export type GetSwapRoutesResponse = {
    routes: unknown;
};

export type GetSwapStatusResponse = {
    fee_costs: Array<SwapStatusFeeCost>;
    from_address: string;
    lifi_explorer_link: string;
    provider: string;
    receiving?: SwapStatusSide;
    sending?: SwapStatusSide;
    status: string;
    sub_status: string;
    sub_status_message: string;
    to_address: string;
    tool: string;
    transaction_id: string;
};

export type GetSwapTokensResponse = {
    tokens: {
        [key: string]: Array<SwapTokenItem>;
    };
};

export type GetSwapToolsResponse = {
    bridges: Array<SwapToolItem>;
    exchanges: Array<SwapToolItem>;
};

export type GetTokenHistoryResponse = {
    history_list?: HistoryList;
};

export type GetTokenListCachedRequest = {
    address: string;
    chains: Array<string>;
};

export type GetTokenListCachedResponse = {
    list: Array<Array<Token>>;
};

export type GetTokenListRequest = {
    address: string;
    chains: Array<string>;
};

export type GetTokenListResponse = {
    list: Array<Array<Token>>;
};

export type GetTokenResponse = {
    amount: string;
    asset: string;
    cex_ids: Array<string>;
    chain: string;
    credit_score?: string;
    decimals: number;
    display_symbol: string;
    fdv?: string;
    id: string;
    identity?: TokenIdentity;
    is_core: boolean;
    is_infinity: boolean;
    is_scam: boolean;
    is_suspicious: boolean;
    is_verified: boolean;
    is_wallet: boolean;
    logo_url: string;
    low_credit_score: boolean;
    name: string;
    optimized_symbol: CurrencyCode;
    price: number;
    price_24h_change: string;
    protocol_id?: string;
    raw_amount: string;
    raw_amount_hex_str: string;
    symbol: CurrencyCode;
    time_at: number;
    total_supply?: string;
    usd_value: string;
};

export type GetTxsIsGaslessRequest = {
    tx_list: Array<Transaction>;
};

export type GetTxsIsGaslessResponse = {
    is_gasless: boolean;
    promotion: unknown;
};

export type GetUserTokenListResponse = {
    list: Array<Array<Token>>;
};

export type GetWalletStatusRequest = {
    address: string;
};

export type GetWalletStatusResponse = {
    is_blocked: boolean;
};

export type HistoryItem = {
    cate_id: string;
    cex_id?: string;
    chain: string;
    id: string;
    idx: number;
    is_scam: boolean;
    other_addr: string;
    project_id?: string;
    receives: Array<ReceiveItem>;
    sends: Array<SendItem>;
    time_at: number;
    token_approve: Array<ApproveItem>;
    tx?: TxDetail;
};

export type HistoryList = {
    cate_dict: {
        [key: string]: Category;
    };
    history_list: Array<HistoryItem>;
    token_dict: {
        [key: string]: Token;
    };
};

export type ListedSite = {
    id: string;
    logo_url: string;
    name: string;
    url: string;
};

export type ParseTxActionType = {
    data: unknown;
    type: string;
};

export type ParseTxContractCallType = {
    contract?: ParseTxContractInfo;
    func: string;
};

export type ParseTxContractInfo = {
    id: string;
    protocol: unknown;
};

export type PreExecStatus = {
    error?: string;
    success: boolean;
};

export type RpcDefaultItem = {
    chainId: string;
    rpcUrl: Array<string>;
    txPushToRPC: boolean;
};

export type ReceiveItem = {
    amount: string;
    from_addr: string;
    price: string;
    token_id: string;
};

export type RegisterInboundReceiverRequest = {
    address: string;
    chain_id: string;
    token_address: string;
};

export type RegisterInboundReceiverResponse = {
    receiver_id: string;
    status: string;
};

export type Route = {
    containsSwitchChain: boolean;
    executionType: string;
    fromAddress: string;
    fromAmount: string;
    fromAmountUSD: string;
    fromChainId: number;
    fromToken?: TokenType3;
    gasCostUSD: string;
    id: string;
    integrator: string;
    steps: Array<RouteStep>;
    tags: Array<string>;
    toAddress: string;
    toAmount: string;
    toAmountMin: string;
    toAmountUSD: string;
    toChainId: number;
    toToken?: TokenType3;
};

export type RouteEstimate = {
    approvalAddress: string;
    executionDuration: number;
    feeCosts: Array<FeeCostType2>;
    fromAmount: string;
    fromAmountUSD: string;
    gasCosts: Array<GasCostType2>;
    toAmount: string;
    toAmountMin: string;
    toAmountUSD: string;
    tool: string;
};

export type RouteStep = {
    estimate?: RouteEstimate;
    id: string;
    tool: string;
    toolDetails?: ToolDetails;
    type: string;
};

export type RpcError = {
    code: number;
    data: unknown;
    message: string;
};

export type SendItem = {
    amount: string;
    price: string;
    to_addr: string;
    token_id: string;
};

export type SubmitDepositRequest = {
    chain_id: string;
    tx_hash: string;
};

export type SubmitDepositResponse = {
    deposit_id: string;
    status: string;
};

export type SwapBalanceItem = {
    balance: string;
    balance_formatted: string;
    chain_id: string;
    decimals: number;
    logo_uri: string;
    name: string;
    native_token: boolean;
    symbol: string;
    token_address: string;
    usd_value: string;
};

export type SwapChainGasPrice = {
    fast: number;
    fastest: number;
    last_updated: number;
    standard: number;
};

export type SwapConnection = {
    from_chain_id: number;
    from_tokens: Array<SwapTokenItem>;
    to_chain_id: number;
    to_tokens: Array<SwapTokenItem>;
};

export type SwapStatusFeeCost = {
    amount: string;
    amount_usd: string;
    description: string;
    included: boolean;
    name: string;
    percentage: string;
};

export type SwapStatusSide = {
    amount: string;
    amount_usd: string;
    chain_id: number;
    gas_amount: string;
    gas_amount_usd: string;
    gas_price: string;
    gas_token?: SwapStatusToken;
    gas_used: string;
    timestamp: number;
    token?: SwapStatusToken;
    tx_hash: string;
    tx_link: string;
};

export type SwapStatusToken = {
    address: string;
    chain_id: number;
    decimals: number;
    logo_uri: string;
    name: string;
    price_usd: string;
    symbol: string;
};

export type SwapToolItem = {
    key: string;
    logo_uri: string;
    name: string;
    supported_chains: Array<number>;
};

export type Token = {
    amount: string;
    asset: string;
    cex_ids: Array<string>;
    chain: string;
    credit_score?: string;
    decimals: number;
    display_symbol: string;
    fdv?: string;
    id: string;
    identity?: TokenIdentity;
    is_core: boolean;
    is_infinity: boolean;
    is_scam: boolean;
    is_suspicious: boolean;
    is_verified: boolean;
    is_wallet: boolean;
    logo_url: string;
    low_credit_score: boolean;
    name: string;
    optimized_symbol: CurrencyCode;
    price: number;
    price_24h_change: string;
    protocol_id?: string;
    raw_amount: string;
    raw_amount_hex_str: string;
    symbol: CurrencyCode;
    time_at: number;
    total_supply?: string;
    usd_value: string;
};

export type TokenIdentity = {
    bridge_ids: Array<string>;
    cex_list: Array<CexItem>;
    chain: string;
    cmc_id: string;
    coingecko_id: string;
    description: string;
    domain_id: string;
    fdv: string;
    id: string;
    is_domain_verified: boolean;
    launchpad_id?: string;
    listed_sites: Array<ListedSite>;
    origin_token?: string;
    relate_domain_ids: Array<string>;
    symbol: string;
    tag_ids: Array<string>;
    token_id: string;
    twitter_id: string;
};

export type TokenInfo = {
    address: string;
    chainId: number;
    coinKey: string;
    decimals: number;
    logoURI: string;
    name: string;
    priceUSD: string;
    symbol: string;
    tags: Array<string>;
};

/**
 * Token represents token information in the responseGasCost represents gas cost breakdown
 */
export type TokenType2 = {
    chain: string;
    credit_score: string;
    decimals: number;
    display_symbol?: string;
    id: string;
    is_core: boolean;
    is_suspicious: boolean;
    is_verified: boolean;
    is_wallet: boolean;
    logo_url: string;
    name: string;
    optimized_symbol: string;
    price: string;
    price_24h_change: string;
    protocol_id: string;
    symbol: string;
    time_at?: number;
    total_supply: string;
};

export type TokenType3 = {
    address: string;
    chainId: number;
    coinKey: string;
    decimals: number;
    logoURI: string;
    name: string;
    priceUSD: string;
    symbol: string;
    tags: Array<string>;
    verificationStatus: string;
    verificationStatusBreakdown: Array<unknown>;
};

export type ToolDetails = {
    key: string;
    logoURI: string;
    name: string;
};

export type Transaction = {
    chainId: number;
    data: string;
    from: string;
    gas: string;
    gasPrice: string;
    maxFeePerGas: string;
    maxPriorityFeePerGas: string;
    nonce: string;
    to: string;
    value: string;
};

export type TransactionData = {
    chainId: number;
    data: string;
    from: string;
    gas: string;
    gasPrice: string;
    maxFeePerGas: string;
    maxPriorityFeePerGas: string;
    nonce: string;
    r: string;
    s: string;
    to: string;
    v: string;
    value: string;
};

export type TxContext = {
    log_id: string;
    origin: string;
    tx: TransactionData;
};

export type TxDetail = {
    eth_gas_fee?: number;
    from_addr: string;
    id: string;
    idx: number;
    message?: string;
    name: string;
    params: Array<unknown>;
    selector?: string;
    status: number;
    to_addr: string;
    usd_gas_fee?: number;
    value: string;
};

export type TypeCallInfo = {
    action: string;
    contract: string;
    contract_protocol_logo_url: string;
    contract_protocol_name: string;
};

export type TypeCancelTx = {
    [key: string]: unknown;
};

export type TypeSendInfo = {
    to_addr: string;
    token?: Token;
    token_amount: number;
    token_symbol: string;
};

export type TypeTokenApprovalInfo = {
    is_infinity: boolean;
    is_nft: boolean;
    nft: unknown;
    spender: string;
    spender_protocol_logo_url: string;
    spender_protocol_name: string;
    token?: Token;
    token_amount: number;
    token_symbol: string;
};

export type SwapChain = {
    blockExplorerUrl: string;
    id: number;
    name: string;
    nativeToken?: SwapToken;
    rpcUrl: string;
    type: string;
};

export type SwapToken = {
    address: string;
    decimals: number;
    priceUSD: string;
    symbol: string;
};

export type SwapTokenItem = {
    address: string;
    decimals: number;
    logoURI: string;
    name: string;
    priceUSD: string;
    symbol: string;
};

export type BuildBridgeTxData = {
    body?: BuildBridgeTxRequest;
    path?: never;
    query?: never;
    url: '/v1/bridge/build_tx';
};

export type BuildBridgeTxResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: BuildBridgeTxResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type BuildBridgeTxResponse2 = BuildBridgeTxResponses[keyof BuildBridgeTxResponses];

export type GetBridgeHistoryListData = {
    body?: never;
    path?: never;
    query?: {
        user_addr?: string;
        start?: number;
        limit?: number;
        is_all?: boolean;
    };
    url: '/v1/bridge/history_list';
};

export type GetBridgeHistoryListResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetBridgeHistoryListResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetBridgeHistoryListResponse2 = GetBridgeHistoryListResponses[keyof GetBridgeHistoryListResponses];

export type GetBridgeQuoteListData = {
    body?: never;
    path?: never;
    query?: {
        aggregator_id?: string;
        user_addr?: string;
        from_chain_id?: string;
        from_token_id?: string;
        from_token_raw_amount?: string;
        to_chain_id?: string;
        to_token_id?: string;
        slippage?: string;
    };
    url: '/v1/bridge/quote_list';
};

export type GetBridgeQuoteListResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetBridgeQuoteListResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetBridgeQuoteListResponse2 = GetBridgeQuoteListResponses[keyof GetBridgeQuoteListResponses];

export type GetBridgeQuoteV2Data = {
    body?: never;
    path?: never;
    query?: {
        aggregator_id?: string;
        user_addr?: string;
        from_chain_id?: string;
        from_token_id?: string;
        from_token_raw_amount?: string;
        to_chain_id?: string;
        to_token_id?: string;
        slippage?: string;
    };
    url: '/v1/bridge/quote_v2';
};

export type GetBridgeQuoteV2Responses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetBridgeQuoteV2Response;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetBridgeQuoteV2Response2 = GetBridgeQuoteV2Responses[keyof GetBridgeQuoteV2Responses];

export type GetTokenListCachedData = {
    body?: GetTokenListCachedRequest;
    path?: never;
    query?: never;
    url: '/v1/cached_list';
};

export type GetTokenListCachedResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetTokenListCachedResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetTokenListCachedResponse2 = GetTokenListCachedResponses[keyof GetTokenListCachedResponses];

export type GetChainRpcData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/chainrpc';
};

export type GetChainRpcResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetChainRpcResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetChainRpcResponse2 = GetChainRpcResponses[keyof GetChainRpcResponses];

export type GetCustomTokenListData = {
    body?: GetCustomTokenListRequest;
    path?: never;
    query?: never;
    url: '/v1/custom_list';
};

export type GetCustomTokenListResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetCustomTokenListResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetCustomTokenListResponse2 = GetCustomTokenListResponses[keyof GetCustomTokenListResponses];

export type GetParseTxData = {
    body?: GetParseTxRequest;
    path?: never;
    query?: never;
    url: '/v1/engine/action/parse_tx';
};

export type GetParseTxResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetParseTxResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetParseTxResponse2 = GetParseTxResponses[keyof GetParseTxResponses];

export type GetCheckTxsData = {
    body?: GetCheckTxsRequest;
    path?: never;
    query?: never;
    url: '/v1/gas_account/check_txs';
};

export type GetCheckTxsResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetCheckTxsResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetCheckTxsResponse2 = GetCheckTxsResponses[keyof GetCheckTxsResponses];

export type GetHypermidQuoteData = {
    body?: never;
    path?: never;
    query?: {
        fromChain?: string;
        toChain?: string;
        fromToken?: string;
        toToken?: string;
        fromAmount?: string;
        fromAddress?: string;
        toAddress?: string;
        slippage?: string;
    };
    url: '/v1/hypermid/quote';
};

export type GetHypermidQuoteResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetHypermidQuoteResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetHypermidQuoteResponse2 = GetHypermidQuoteResponses[keyof GetHypermidQuoteResponses];

export type GetHypermidRoutesData = {
    body?: never;
    path?: never;
    query?: {
        fromChain?: string;
        toChain?: string;
        fromToken?: string;
        toToken?: string;
        fromAmount?: string;
        fromAddress?: string;
        toAddress?: string;
        slippage?: string;
        order?: string;
    };
    url: '/v1/hypermid/routes';
};

export type GetHypermidRoutesResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetHypermidRoutesResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetHypermidRoutesResponse2 = GetHypermidRoutesResponses[keyof GetHypermidRoutesResponses];

export type GetIpInfoData = {
    body?: never;
    path?: never;
    query?: {
        ipAddress?: string;
    };
    url: '/v1/ip';
};

export type GetIpInfoResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetIpInfoResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetIpInfoResponse2 = GetIpInfoResponses[keyof GetIpInfoResponses];

export type GetTokenListData = {
    body?: GetTokenListRequest;
    path?: never;
    query?: never;
    url: '/v1/list';
};

export type GetTokenListResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetTokenListResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetTokenListResponse2 = GetTokenListResponses[keyof GetTokenListResponses];

export type CheckServiceabilityData = {
    body?: never;
    path?: never;
    query?: {
        ipAddress?: string;
    };
    url: '/v1/serviceability';
};

export type CheckServiceabilityResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: CheckServiceabilityResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type CheckServiceabilityResponse2 = CheckServiceabilityResponses[keyof CheckServiceabilityResponses];

export type GetSwapBalancesData = {
    body?: never;
    path?: never;
    query?: {
        address?: string;
        /**
         * comma-separated chain IDs, e.g. "1,137,42161"
         */
        chain_ids?: string;
    };
    url: '/v1/swap/balances';
};

export type GetSwapBalancesResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetSwapBalancesResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetSwapBalancesResponse2 = GetSwapBalancesResponses[keyof GetSwapBalancesResponses];

export type GetSwapChainsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/swap/chains';
};

export type GetSwapChainsResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetSwapChainsResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetSwapChainsResponse2 = GetSwapChainsResponses[keyof GetSwapChainsResponses];

export type GetSwapConnectionsData = {
    body?: never;
    path?: never;
    query?: {
        from_chain_id?: string;
        to_chain_id?: string;
        from_token_id?: string;
        to_token_id?: string;
    };
    url: '/v1/swap/connections';
};

export type GetSwapConnectionsResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetSwapConnectionsResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetSwapConnectionsResponse2 = GetSwapConnectionsResponses[keyof GetSwapConnectionsResponses];

export type GetDepositStatusData = {
    body?: never;
    path?: never;
    query?: {
        deposit_id?: string;
    };
    url: '/v1/swap/deposit/status';
};

export type GetDepositStatusResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetDepositStatusResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetDepositStatusResponse2 = GetDepositStatusResponses[keyof GetDepositStatusResponses];

export type SubmitDepositData = {
    body?: SubmitDepositRequest;
    path?: never;
    query?: never;
    url: '/v1/swap/deposit/submit';
};

export type SubmitDepositResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: SubmitDepositResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type SubmitDepositResponse2 = SubmitDepositResponses[keyof SubmitDepositResponses];

export type GetDexSwapQuoteData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
        chain_id?: string;
        dex_id?: string;
        pay_token_id?: string;
        pay_token_raw_amount?: string;
        receive_token_id?: string;
        slippage?: string;
        fee?: boolean;
    };
    url: '/v1/swap/dex_quote';
};

export type GetDexSwapQuoteResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetDexSwapQuoteResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetDexSwapQuoteResponse2 = GetDexSwapQuoteResponses[keyof GetDexSwapQuoteResponses];

export type ExecuteSwapData = {
    body?: ExecuteSwapRequest;
    path?: never;
    query?: never;
    url: '/v1/swap/execute';
};

export type ExecuteSwapResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: ExecuteSwapResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type ExecuteSwapResponse2 = ExecuteSwapResponses[keyof ExecuteSwapResponses];

export type GetSwapGasPricesData = {
    body?: never;
    path?: never;
    query?: {
        chains?: string;
    };
    url: '/v1/swap/gas_prices';
};

export type GetSwapGasPricesResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetSwapGasPricesResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetSwapGasPricesResponse2 = GetSwapGasPricesResponses[keyof GetSwapGasPricesResponses];

export type RegisterInboundReceiverData = {
    body?: RegisterInboundReceiverRequest;
    path?: never;
    query?: never;
    url: '/v1/swap/inbound/receiver';
};

export type RegisterInboundReceiverResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: RegisterInboundReceiverResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type RegisterInboundReceiverResponse2 = RegisterInboundReceiverResponses[keyof RegisterInboundReceiverResponses];

export type GetSwapQuoteData = {
    body?: never;
    path?: never;
    query?: {
        fromChain?: string;
        toChain?: string;
        fromToken?: string;
        toToken?: string;
        fromAmount?: string;
        fromAddress?: string;
        toAddress?: string;
        slippage?: string;
    };
    url: '/v1/swap/quote';
};

export type GetSwapQuoteResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetSwapQuoteResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetSwapQuoteResponse2 = GetSwapQuoteResponses[keyof GetSwapQuoteResponses];

export type GetSwapRoutesData = {
    body?: never;
    path?: never;
    query?: {
        fromChain?: string;
        toChain?: string;
        fromToken?: string;
        toToken?: string;
        fromAmount?: string;
        fromAddress?: string;
        toAddress?: string;
        slippage?: string;
        order?: string;
    };
    url: '/v1/swap/routes';
};

export type GetSwapRoutesResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetSwapRoutesResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetSwapRoutesResponse2 = GetSwapRoutesResponses[keyof GetSwapRoutesResponses];

export type GetSwapStatusData = {
    body?: never;
    path?: never;
    query?: {
        txHash?: string;
        fromChain?: string;
        toChain?: string;
    };
    url: '/v1/swap/status';
};

export type GetSwapStatusResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetSwapStatusResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetSwapStatusResponse2 = GetSwapStatusResponses[keyof GetSwapStatusResponses];

export type GetSwapTokensData = {
    body?: never;
    path?: never;
    query?: {
        chain?: string;
    };
    url: '/v1/swap/tokens';
};

export type GetSwapTokensResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetSwapTokensResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetSwapTokensResponse2 = GetSwapTokensResponses[keyof GetSwapTokensResponses];

export type GetSwapToolsData = {
    body?: never;
    path?: never;
    query?: {
        chains?: string;
    };
    url: '/v1/swap/tools';
};

export type GetSwapToolsResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetSwapToolsResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetSwapToolsResponse2 = GetSwapToolsResponses[keyof GetSwapToolsResponses];

export type AddUserTokenData = {
    body?: AddUserTokenRequest;
    path?: never;
    query?: never;
    url: '/v1/user/custom_token';
};

export type AddUserTokenResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: AddUserTokenResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type AddUserTokenResponse2 = AddUserTokenResponses[keyof AddUserTokenResponses];

export type GetTxnHistoryData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
        chain_id?: string;
        token_id?: string;
        page_count?: number;
        start_time?: number;
    };
    url: '/v1/user/history_list';
};

export type GetTxnHistoryResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetTokenHistoryResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetTxnHistoryResponse = GetTxnHistoryResponses[keyof GetTxnHistoryResponses];

export type GetTokenData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
        token_id?: string;
        chain_id?: string;
    };
    url: '/v1/user/token';
};

export type GetTokenResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetTokenResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetTokenResponse2 = GetTokenResponses[keyof GetTokenResponses];

export type GetUserTokenListData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
        chain_id?: string;
        is_all?: boolean;
    };
    url: '/v1/user/token_list';
};

export type GetUserTokenListResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetUserTokenListResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetUserTokenListResponse2 = GetUserTokenListResponses[keyof GetUserTokenListResponses];

export type GetSearchTokenData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
        q?: string;
        chain_id?: string;
        has_balance?: boolean;
        is_all?: boolean;
    };
    url: '/v1/user/token_search';
};

export type GetSearchTokenResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetSearchTokenResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetSearchTokenResponse2 = GetSearchTokenResponses[keyof GetSearchTokenResponses];

export type GetChainBalanceListData = {
    body?: never;
    path?: never;
    query?: {
        force_fetch?: boolean;
        id?: string;
    };
    url: '/v1/user/total_balance';
};

export type GetChainBalanceListResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetChainBalanceListResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetChainBalanceListResponse2 = GetChainBalanceListResponses[keyof GetChainBalanceListResponses];

export type GetEthRpcData = {
    body?: GetEthRpcRequest;
    path?: never;
    query?: {
        origin?: string;
        method?: string;
        chain_id?: string;
    };
    url: '/v1/wallet/eth_rpc';
};

export type GetEthRpcResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetEthRpcResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetEthRpcResponse2 = GetEthRpcResponses[keyof GetEthRpcResponses];

export type GetGasPriceStatsData = {
    body?: never;
    path?: never;
    query?: {
        chain_id?: string;
    };
    url: '/v1/wallet/gas_price_stats';
};

export type GetGasPriceStatsResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetGasPriceStatsResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetGasPriceStatsResponse2 = GetGasPriceStatsResponses[keyof GetGasPriceStatsResponses];

export type GetPreExecTxnData = {
    body?: GetPreExecTxnRequest;
    path?: never;
    query?: never;
    url: '/v1/wallet/pre_exec_tx';
};

export type GetPreExecTxnResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetPreExecTxnResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetPreExecTxnResponse2 = GetPreExecTxnResponses[keyof GetPreExecTxnResponses];

export type GetTxsIsGaslessData = {
    body?: GetTxsIsGaslessRequest;
    path?: never;
    query?: never;
    url: '/v1/wallet/txs_is_gasless';
};

export type GetTxsIsGaslessResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetTxsIsGaslessResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetTxsIsGaslessResponse2 = GetTxsIsGaslessResponses[keyof GetTxsIsGaslessResponses];

export type GetWalletStatusData = {
    body?: GetWalletStatusRequest;
    path?: never;
    query?: never;
    url: '/v1/wallet_status';
};

export type GetWalletStatusResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetWalletStatusResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetWalletStatusResponse2 = GetWalletStatusResponses[keyof GetWalletStatusResponses];

export type GetGasFeeData = {
    body?: GetGasFeeRequest;
    path?: never;
    query?: never;
    url: '/v2/wallet/gas_market';
};

export type GetGasFeeResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetGasFeeResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetGasFeeResponse2 = GetGasFeeResponses[keyof GetGasFeeResponses];

export type GetSubmitTxData = {
    body?: GetSubmitTxRequest;
    path?: never;
    query?: never;
    url: '/v2/wallet/submit_tx';
};

export type GetSubmitTxResponses = {
    /**
     * OK
     */
    200: {
        code: number;
        data: GetSubmitTxResponse;
        displayError?: string;
        message: string;
        traceId: string;
    };
};

export type GetSubmitTxResponse2 = GetSubmitTxResponses[keyof GetSubmitTxResponses];
