/**
 * API Enums
 *
 * Centralized enum definitions extracted from OpenAPI specifications.
 * These enums are shared across all apps to avoid duplication.
 *
 * Auto-generated by scripts/openapi-postgen.js
 * Run `make api-spec` to regenerate.
 */

export enum AssociateRole {
  UNKNOWN = "unknown",
  OWNER = "owner",
}

export enum AssociateType {
  UNKNOWN = "unknown",
  CUSTOMER = "customer",
  PARTNER = "partner",
  MERCHANT = "merchant",
  RAMPNOW = "rampnow",
}

export enum AuthenticationType {
  TOTP = "totp",
}

export enum DocSetType {
  UNKNOWN = "unknown",
  CERTIFICATE_OF_GOOD_STANDING = "certificate_of_good_standing",
  CERTIFICATE_OF_INCUMBENCY = "certificate_of_incumbency",
  CERTIFICATE_OF_INCORPORATION = "certificate_of_incorporation",
  BUSINESS_LICENSE = "business_license",
  COMMERCIAL_REGISTER_EXTRACT = "commercial_register_extract",
  REGISTER_OF_SHAREHOLDERS = "register_of_shareholders",
  MEMORANDUM_AND_ARTICLES_OF_ASSOCIATION = "memorandum_and_articles_of_association",
  INTERNAL_CONTROL_PROCEDURES = "internal_control_procedures",
  AML_POLICIES = "aml_policies",
  COMPLIANCE_OFFICER_DETAILS = "compliance_officer_details",
  UBO = "ubo",
  PASSPORT = "passport",
  UTILITY_BILL = "utility_bill",
  PEP_DECLARATION = "pep_declaration",
  SANCTIONS_EXPOSURE = "sanctions_exposure",
  FINANCIAL = "financial",
  AADHAR_CARD = "aadhar_card",
  PAN_CARD = "pan_card",
  NATIONAL_ID = "national_id",
  OTHER = "other",
}

export enum EntityProvider {
  UNKNOWN = "unknown",
  RAMPNOW = "rampnow",
  ZEN = "zen",
  JANUAR = "januar",
  COINBASE_EXCHANGE = "coinbase_exchange",
  COINBASE_PRIME = "coinbase_prime",
  OKX = "okx",
  KRAKEN = "kraken",
  BINANCE = "binance",
  FIREBLOCKS = "fireblocks",
  BYBIT = "bybit",
  VOLT = "volt",
  PAYSAFE = "paysafe",
  CRYPTO = "crypto",
  CUSTOMER = "customer",
  SUMSUB = "sumsub",
  DUMMY = "dummy",
  FIND_IP = "find_ip",
  TRUSTFULL = "trustfull",
  SCORECHAIN = "scorechain",
  VERIFF = "veriff",
  GATE_IO = "gate_io",
  MEXC = "mexc",
  NOW_NODES = "now_nodes",
  IVY = "ivy",
  BANXA = "banxa",
  ONRAMP = "onramp",
  THIRDWEB = "thirdweb",
  WERT = "wert",
  BANXA_DAPP = "banxa_dapp",
  LEOPAY = "leopay",
}

export enum EntityType {
  UNKNOWN = "unknown",
  PAYMENT_GATEWAY = "payment_gateway",
  EXCHANGE_ORDER = "exchange_order",
  CRYPTO_TRANSFER = "crypto_transfer",
  EXCHANGE_WITHDRAWAL = "exchange_withdrawal",
  EXCHANGE_TRANSFER = "exchange_transfer",
  KYC = "kyc",
  IP_INFO = "ip_info",
  KYT = "kyt",
  FIAT_TRANSFER = "fiat_transfer",
  EXCHANGE_CONVERSION = "exchange_conversion",
  RPC_NODE = "rpc_node",
  CRYPTO_APPROVE = "crypto_approve",
  CRYPTO_BRIDGE = "crypto_bridge",
  CRYPTO_SWAP = "crypto_swap",
  OFFRAMP = "offramp",
  PAYROLL = "payroll",
  SENDOUT = "sendout",
}

export enum GenderType {
  UNKNOWN = "unknown",
  MALE = "male",
  FEMALE = "female",
}

export enum KycStatus {
  UNKNOWN = "unknown",
  STARTED = "started",
  APPROVED = "approved",
  DECLINED = "declined",
  EXPIRED = "expired",
  ABANDONED = "abandoned",
  REVIEW = "review",
  PENDING = "pending",
  RESUBMISSION = "resubmission",
  RESET = "reset",
  LEVEL_CHANGED = "level_changed",
}

export enum OrderMode {
  REGULAR = "regular",
  CHECKOUT = "checkout",
  SERVER = "server",
}

export enum OrderStatus {
  UNKNOWN = "unknown",
  CREATED = "created",
  PROCESSING = "processing",
  COMPLETED = "completed",
  PARTIALLY_FAILED = "partially_failed",
  FAILED = "failed",
  EXPIRED = "expired",
  CANCELED = "canceled",
  PAYMENT_FAILED = "payment_failed",
  PAYMENT_PROCESSING = "payment_processing",
  BLOCKED = "blocked",
}

export enum OrderType {
  UNKNOWN = "unknown",
  BUY = "buy",
  SELL = "sell",
  SWAP = "swap",
  PAYMENT = "payment",
  REFILL = "refill",
  PAYOUT = "payout",
  CROSS_BORDER = "cross_border",
  PAYROLL = "payroll",
  SENDOUT = "sendout",
}

export enum PartnerStatus {
  ACTIVE = "active",
  BLOCKED = "blocked",
}

export enum PaymentStatus {
  UNKNOWN = "unknown",
  CREATED = "created",
  PENDING = "pending",
  AUTHORIZED = "authorized",
  ACCEPTED = "accepted",
  RECEIVED = "received",
  REJECTED = "rejected",
  EXPIRED = "expired",
  CANCELED = "canceled",
  FAILED = "failed",
  REFUNDED = "refunded",
  CHARGEBACKED = "chargebacked",
  REVIEW = "review",
  PROCESSING_FAILED = "processing_failed",
}

export enum PayoutStatus {
  UNKNOWN = "unknown",
  CREATED = "created",
  REJECTED = "rejected",
  CANCELED = "canceled",
  ACCEPTED = "accepted",
  PAID = "paid",
}

export enum QuoteType {
  DST_AMOUNT_UNKNOWN = "dst_amount_unknown",
  DST_AMOUNT_NET = "dst_amount_net",
  SRC_AMOUNT_NET = "src_amount_net",
}

export enum RefillMode {
  UNKNOWN = "unknown",
  SWEEP_IN = "sweep_in",
  SWEEP_OUT = "sweep_out",
}

export enum RefillStatus {
  UNKNOWN = "unknown",
  ACTIVE = "active",
  INACTIVE = "inactive",
}

export enum RefillType {
  UNKNOWN = "unknown",
  ORDER_LIQUIDITY = "order_liquidity",
  NETWORK_LIQUIDITY = "network_liquidity",
}

export enum RefundStatus {
  UNKNOWN = "unknown",
  CREATED = "created",
  PENDING = "pending",
  REJECTED = "rejected",
  CANCELED = "canceled",
  ACCEPTED = "accepted",
  AUTHORIZED = "authorized",
  EXPIRED = "expired",
}

export enum ReviewStatus {
  UNKNOWN = "unknown",
  PENDING = "pending",
  APPROVED = "approved",
  REJECTED = "rejected",
}

export enum RiskStatus {
  UNKNOWN = "unknown",
  INITIATED = "initiated",
  LOW = "low",
  HIGH = "high",
  MODERATE = "moderate",
  NO_SUPPORT = "no_support",
}

export enum RouteStatus {
  UNKNOWN = "unknown",
  ACTIVE = "active",
  INACTIVE = "inactive",
  DEPRECATED = "deprecated",
}

export enum RouteType {
  REGULAR = "regular",
  DAPP = "dapp",
}

export enum SettingStatus {
  UNKNOWN = "unknown",
  ACTIVE = "active",
  INACTIVE = "inactive",
  SUSPENDED = "suspended",
}

export enum TransactionFlow {
  UNKNOWN = "unknown",
  FIAT_IN = "fiat_in",
  FIAT_OUT = "fiat_out",
  FIAT_TRANSFER = "fiat_transfer",
  CRYPTO_IN = "crypto_in",
  CRYPTO_OUT = "crypto_out",
  CRYPTO_TRANSFER = "crypto_transfer",
  EXCHANGE = "exchange",
  WALLET_TRANSFER = "wallet_transfer",
  CRYPTO_SWAP = "crypto_swap",
  CRYPTO_BRIDGE = "crypto_bridge",
  CRYPTO_APPROVE = "crypto_approve",
}

export enum TransactionStatus {
  UNKNOWN = "unknown",
  STARTED = "started",
  PROCESSING = "processing",
  FAILED = "failed",
  COMPLETED = "completed",
}

export enum TravelRuleStatus {
  UNKNOWN = "unknown",
  EXPIRED = "expired",
  INDETERMINATE = "indeterminate",
  VASP_NOT_FOUND = "vasp_not_found",
  PENDING = "pending",
  MISMATCH = "mismatch",
  COMPLETED = "completed",
}

export enum UserStatus {
  UNKNOWN = "unknown",
  ACTIVE = "active",
  INACTIVE = "inactive",
  BLOCKED = "blocked",
}

export enum WalletAction {
  NONE = "none",
  UPDATE_BALANCE = "update_balance",
  UPDATE_ACTUAL_BALANCE = "update_actual_balance",
  UPDATE_AVAILABLE_BALANCE = "update_available_balance",
}

export enum WalletCustodyType {
  UNKNOWN = "unknown",
  HOSTED = "hosted",
  UNHOSTED = "unhosted",
}

export enum WalletStatus {
  ACTIVE = "active",
  INACTIVE = "inactive",
  BLOCKED = "blocked",
}

export enum WalletType {
  UNKNOWN = "unknown",
  TRADING = "trading",
  FUNDING = "funding",
  NON_CUSTODIAL = "non_custodial",
  EXTERNAL = "external",
  TREASURY = "treasury",
  BANK = "bank",
  INTERMEDIATE = "intermediate",
}
